name: "Add doc diff to PR comment"

on:
  workflow_run:
    workflows: ["PsyNeuLink Docs Compare"]
    types:
      - completed

jobs:
  post-comment:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
          github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: 'Download artifact'
        uses: actions/github-script@v4.0.2
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name.startsWith("compare")
            }).slice(-1)[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));

      - name: Unzip artifact
        run: unzip pr.zip

      - name: Post comment with docs diff
        uses: actions/github-script@v4.0.2
        with:
          script: |
            var fs = require("fs");
            var issue_number = Number(fs.readFileSync('./PR_NR'));
            var os = fs.readFileSync('./PR_OS', 'utf8').trim();
            var python = fs.readFileSync('./PR_PYTHON_VERSION', 'utf8').trim();
            var text = fs.readFileSync("./result.diff").slice(0,16384);

            // basic input checks
            console.assert(['ubuntu-latest', 'windows-latest', 'macos-latest'].includes(os), 'Unexpected os: %s', os);
            console.assert(['3.6', '3.7', '3.8'].includes(python), 'Unexpected python: %s', python);
            console.assert(!text.includes('```'), 'Invalid diff!');

            console.log('Posting diff to PR:' + issue_number)

            github.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This PR causes the following changes to the html docs (' + os + ', python-' + python + '):\n```\n' + text + '\n...\n```\nSee CI logs for the full diff.'
            })

