name: Enable All Workflows

on:
  schedule:
    # arbitrary time weekly
    # anything less than 60 days should work though
    - cron: "17 0 * * 2"
  workflow_dispatch:

jobs:
  enable_workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run github-keepalive.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        working-directory: ./bin
        run: pwd && ls -la && ls -la .. && bash -x github-keepalive.sh
