name: PsyNeuLink Docs Compare

on: pull_request

jobs:
  docs-build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]
        pnl-version: [ 'base', 'merge']

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout merge commit
      uses: actions/checkout@v2.3.4
      if: ${{ matrix.pnl-version == 'merge' }}
      with:
        fetch-depth: 10
        ref: ${{ github.ref }}

    - name: Checkout pull base
      uses: actions/checkout@v2.3.4
      if: ${{ matrix.pnl-version == 'base' }}
      with:
        fetch-depth: 10
        ref: ${{ github.base_ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-architecture }}

    - name: Get pip cache location
      shell: bash
      id: pip_cache
      run: |
        python -m pip install -U pip
        python -m pip --version
        echo ::set-output name=pip_cache_dir::$(python -m pip cache dir)

    - name: Wheels cache
      uses: actions/cache@v2.1.6
      with:
        path: ${{ steps.pip_cache.outputs.pip_cache_dir }}/wheels
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-x64-pip-wheels-doc-compare-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-python-${{ matrix.python-version }}-x64-pip-wheels-doc-compare
          ${{ runner.os }}-python-${{ matrix.python-version }}-x64-pip-wheels-v2

    # We need to install all PNL deps since docs config imports psyneulink module
    - name: Install local, editable PNL package
      uses: ./.github/actions/install-pnl
      with:
        features: 'doc'

    - name: Add git tag
      # The generated docs include PNL version,
      # set it to a fixed value to prevent polluting the diff
      run: git tag 'v999.999.999.999'

    - name: Build docs
      run: sphinx-build -b html -aE -j auto docs/source pnl-html

    - name: Upload generated docs
      uses: actions/upload-artifact@v2.2.3
      with:
        name: docs-${{ matrix.pnl-version }}-${{ matrix.os }}-${{ matrix.python-version }}
        path: pnl-html
        retention-days: 1

  docs-compare:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    needs: [docs-build]

    steps:

    - name: Download generated base docs
      uses: actions/download-artifact@v2
      with:
        name: docs-base-${{ matrix.os }}-${{ matrix.python-version }}
        path: docs-base

    - name: Download generated merge docs
      uses: actions/download-artifact@v2
      with:
        name: docs-merge-${{ matrix.os }}-${{ matrix.python-version }}
        path: docs-merge

    - name: Compare
      shell: bash
      run: |
        mkdir -p compare
        # Store the resulting diff, or 'No differences!' to and output file
        # The 'or true' part is needed to workaround 'pipefail' flag used by github-actions
        (diff -r docs-base docs-merge && echo 'No differences!' || true) | tee ./compare/result.diff
        # save PR number
        echo ${{ github.event.number }} > ./compare/PR_NR
        echo ${{ matrix.os }} > ./compare/PR_OS
        echo ${{ matrix.python-version }} > ./compare/PR_PYTHON_VERSION

    - name: Upload comparison results
      uses: actions/upload-artifact@v2.2.3
      with:
        name: compare-${{ matrix.os }}-${{ matrix.python-version }}
        path: compare
        retention-days: 1
